name: responsive_mpa_web
description: Flutter plugin for responsive web application with Multi Page Application experience.
version: 0.0.3
homepage: https://github.com/ozaenzenzen/responsive_mpa_web

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

platforms:
  web:
